########################################
# TEST API NODE + MYSQL
########################################

@baseUrl = http://localhost:3000/api
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIzLCJpYXQiOjE3ODE4NDIwODZ9.qPLt9NVatG9kV-7WwatJRxqDQYRLA6gRSpJ4OsthGWM

########################################
# TEST SERVER
########################################
GET {{baseUrl}}/test


########################################
# CATEGORIES
########################################

### Obtener todas las categorías
GET {{baseUrl}}/categories


########################################
# ARTICLES
########################################

### Obtener todos los artículos (con filtros opcionales)
GET {{baseUrl}}/articles

###

### Obtener artículo por ID
GET {{baseUrl}}/articles/1

###

### Crear artículo
POST {{baseUrl}}/articles
Content-Type: application/json

{
  "titulo": "Caña de pescar",
  "descripcion": "Caña en buen estado",
  "foto": "imagen.jpg",
  "precio": 50,
  "estado_articulo": "Nuevo",
  "estado_revision": "Publicado",
  "perfil_id": 1,
  "categoria_id": 1
}

###

### Comprar artículo
PUT {{baseUrl}}/articles/1/buy

###

### Reservar artículo
PUT {{baseUrl}}/articles/1/reserve


########################################
# FAVORITES
########################################

### Añadir a favoritos
POST {{baseUrl}}/favorites
Content-Type: application/json

{
  "perfil_id": 1,
  "articulo_id": 1
}


########################################
# MESSAGES
########################################

### Enviar mensaje
POST {{baseUrl}}/messages
Content-Type: application/json

{
  "texto_mensaje": "Hola, sigue disponible?",
  "emisor_id": 1,
  "receptor_id": 2,
  "articulo_id": 1
}


########################################
# REPORTS
########################################

### Crear reporte
POST {{baseUrl}}/reports
Content-Type: application/json

{
  "motivo": "Artículo sospechoso",
  "denunciante_id": 1,
  "denunciado_id": 2,
  "articulo_id": 1
}


########################################
# REVIEWS
########################################

### Crear valoración
POST {{baseUrl}}/reviews
Content-Type: application/json

{
  "puntuacion": 5,
  "comentario": "Muy buen vendedor",
  "emisor_id": 1,
  "receptor_id": 2,
  "articulo_id": 1
}


########################################
# REVIEWS
########################################

### Crear usuario
POST {{baseUrl}}/register
Content-Type: application/json

{
  "username": "username1",
  "name" : "name1",
  "surname": "surname1",
  "email": "username1@gmail.com",
  "password": "12345678",
  "rol":1
}

### Login usuario
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "username1@gmail.com",
  "password": "12345678"

}

### autorization
GET {{baseUrl}}/categories
Authorization: {{TOKEN}}