########################################
# TEST API NODE + MYSQL
########################################

@baseUrl = http://localhost:3000/api
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIxLCJyb2xlIjoyLCJpYXQiOjE3ODE5Nzg2MTB9.OvqwLVCIF1ICenziLdWeMSZWzhvoS4Tv4afQUYEGQSQ

########################################
# TEST SERVER
########################################
GET {{baseUrl}}/test


########################################
# CATEGORIES
########################################

### Obtener todas las categorías
GET {{baseUrl}}/categories


########################################
# ARTICLES
########################################

### Obtener todos los artículos (con filtros opcionales)
GET {{baseUrl}}/articles

###

### Obtener artículo por ID
GET {{baseUrl}}/articles/1

###

### Crear artículo
POST {{baseUrl}}/articles
Content-Type: application/json

{
  "titulo": "Caña de pescar",
  "descripcion": "Caña en buen estado",
  "foto": "imagen.jpg",
  "precio": 50,
  "estado_articulo": "Nuevo",
  "estado_revision": "Publicado",
  "perfil_id": 1,
  "categoria_id": 1
}

###

### Comprar artículo
PUT {{baseUrl}}/articles/1/buy

###

### Reservar artículo
PUT {{baseUrl}}/articles/1/reserve


########################################
# FAVORITES
########################################

### Añadir a favoritos
POST {{baseUrl}}/favorites
Content-Type: application/json

{
  "perfil_id": 1,
  "articulo_id": 1
}


########################################
# MESSAGES
########################################

### Enviar mensaje
POST {{baseUrl}}/messages
Content-Type: application/json

{
  "texto_mensaje": "Hola, sigue disponible?",
  "emisor_id": 1,
  "receptor_id": 2,
  "articulo_id": 1
}

########################################
# REPORTS
########################################

### Reportes pendientes
GET {{baseUrl}}/reports?estado=Pendiente
Authorization: {{TOKEN}}

### Reportes retirado
GET {{baseUrl}}/reports?estado=Revisado_Retirado
Authorization: {{TOKEN}}

### Reportes mantenido
GET {{baseUrl}}/reports?estado=Revisado_Mantenido
Authorization: {{TOKEN}}

### Reporte por id
GET  {{baseUrl}}/reports/1
Authorization: {{TOKEN}}

### Estadísticas estados
GET {{baseUrl}}/reports/stadistics
Authorization: {{TOKEN}}

### Actualizar estado del reporte
PUT {{baseUrl}}/reports/1
Authorization: {{TOKEN}}
Content-Type: application/json

{
  "estado_reporte": "Revisado_Mantenido",
  "resolucion_comentario": "Producto totalmente apto y verificado"
}

### Crear reporte
POST {{baseUrl}}/reports
Content-Type: application/json

{
  "motivo": "Artículo sospechoso",
  "denunciante_id": 1,
  "denunciado_id": 2,
  "articulo_id": 1
}


########################################
# REVIEWS
########################################

### Crear valoración
POST {{baseUrl}}/reviews
Content-Type: application/json

{
  "puntuacion": 5,
  "comentario": "Muy buen vendedor",
  "emisor_id": 1,
  "receptor_id": 2,
  "articulo_id": 1
}


########################################
# REVIEWS
########################################

### Login usuario
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "moderatoruser@gmail.com",
  "password": "12345678"
}

### autorization
GET {{baseUrl}}/categories
Authorization: {{TOKEN}}


########################################
# REVIEWS
########################################

POST {{baseUrl}}/users/register
Content-Type: application/json

{
  "email": "465654@gmail.com",
  "lastname": "lopes garsia",
  "name": "Álvaro",
  "password": "1234",
  "repetPassword": "1234",
  "username": "alvarolg"

}

### Resetear contraseña
PATCH {{baseUrl}}/users/reset-password
Content-Type: application/json

{
  "email": "465654@gmail.com",
  "newPassword": "Nueva1234",
  "repeatPassword": "Nueva1234"
}
