export const MESSAGE_TEXT = {
  auth: {
    loginRequiredFields: 'Email y password son campos requeridos',
    loginInvalidCredentials: 'Email y/o Password incorrecto',
    resetRequiredFields: 'Email, usuario, nueva contraseña y repetir contraseña son campos requeridos',
    resetPasswordMismatch: 'Las contraseñas no coinciden',
    resetPasswordSuccess: 'Contraseña actualizada correctamente',
    resetPasswordError: 'No se pudo actualizar contraseña',
  },
  home: {
    categoriesLoadError: 'No se han podido cargar las categorías',
    latestProductsLoadError: 'No se han podido cargar los últimos productos',
    promotionProductsLoadError: 'No se han podido cargar los productos en promoción',
  },
  catalog: {
    publishLabel: 'Publicar',
  },
  articleForm: {
    categoriesLoadError: 'No se han podido cargar las categorías',
    loginRequired: 'Necesitas haber iniciado sesión antes de querer hacer esta acción',
    imageUrlInvalid: 'La foto debe ser una URL válida de máximo 200 caracteres',
    createSuccess: '¡Éxito! Gracias por utilizar Brickswap. El artículo se ha subido correctamente.',
    createError: '¡Error! El artículo no se ha podido subir a Brickswap.',
  },
  review: {
    loginRequired: 'Debes estar logueado para valorar.',
    sendError: 'Error al enviar la valoración',
  },
  messages: {
    pageTitle: 'Mensajes',
    staffDescription: 'Reportes creados por los usuarios',
    userDescription: 'Tus conversaciones y respuestas de reportes',
    tabAll: 'Todos',
    tabPending: 'Pendiente',
    tabResolved: 'Resuelto',
    tabUnread: 'Sin leer',
    tabRead: 'Leído',
    loadingData: 'Cargando datos...',
    loadingConversation: 'Cargando conversación...',
    noReports: 'No hay reportes para mostrar.',
    noConversations: 'No hay conversaciones para mostrar.',
    loggedUserError: 'No se ha podido identificar al usuario logueado',
    unsupportedUserType: 'Tipo de usuario no soportado',
    loadDataError: 'No se han podido cargar los datos',
    defaultUser: 'Usuario',
    moderationContact: 'Moderación',
    reportPending: 'Reporte pendiente',
    reportResolved: 'Reporte resuelto',
    reportReasonPrefix: 'Motivo',
    reportResolutionPrefix: 'Resolución',
    articleFallbackPrefix: 'Artículo',
    now: 'Ahora',
    oneDayAgo: 'Hace 1 día',
    minutesAgo: 'Hace',
    hoursAgo: 'Hace',
    daysAgo: 'Hace',
    priceOfferLabel: 'Propuesta de precio',
    deliveryMethodLabel: 'Método de entrega',
    priceOfferPrompt: 'Introduce la propuesta de precio',
    priceOfferNumericError: 'Campo numérico',
    deliveryMethodPrompt: 'Introduce el método de entrega',
    priceOfferModalTitle: 'Proponer precio',
    priceOfferModalLabel: 'Precio',
    priceOfferModalSubmit: 'Enviar precio',
    deliveryMethodModalTitle: 'Proponer entrega',
    deliveryMethodModalLabel: 'Método de entrega',
    deliveryMethodModalSubmit: 'Enviar entrega',
    modalCancelLabel: 'Cancelar',
    modalRequiredError: 'Este campo es obligatorio',
    sendToComplainant: 'Enviar mensaje',
    reportDecisionPlaceholder: 'Escribe una respuesta o explica el motivo de la decisión...',
    keepReportedArticle: 'Aprobar artículo',
    removeReportedArticle: 'Retirar artículo',
    updateReportError: 'Error al actualizar el estado del reporte',
    sendReportMessageError: 'Error al enviar el mensaje al denunciante',
    composerLabel: 'Mensaje',
    composerPlaceholder: 'Escribe un mensaje...',
    composerSendAria: 'Enviar mensaje',
    actionsAria: 'Acciones de conversacion',
    threadAria: 'Mensajes de la conversacion',
    emptyAria: 'Conversacion sin mensajes',
    conversationAria: 'Conversacion',
    proposePrice: 'Proponer precio',
    proposeDelivery: 'Proponer entrega',
    buy: 'Comprar',
    emptyConversation:
      'Inicia la conversación enviando un mensaje, haciendo una oferta de precio o proponiendo un método de entrega.',
  },
  articleDetail: {
    backLabel: 'Volver',
    detailsAria: 'Datos del artículo',
    actionsAria: 'Acciones del artículo',
    categoryFallback: 'Categoría',
    sellerFallback: 'Vendedor',
    favoriteLabel: 'Añadir a favoritos',
    buyNowLabel: 'Comprar ahora',
    reserveLabel: 'Reservar',
    chatLabel: 'Chatear',
    reportLabel: 'Denunciar',
    reviewPurchaseLabel: 'Valorar mi compra',
    actionLoginRequired: 'Necesitas haber iniciado sesión antes de querer hacer esta acción',
    buySuccess: 'El artículo ha sido comprado correctamente',
    buyUnavailable: 'Artículo no disponible para la compra',
    reserveSuccess: '¡Artículo reservado con éxito! El producto se ha marcado como reservado.',
    reserveUnavailable: 'Artículo no disponible para la reserva',
    operationError: 'Error al procesar la operación, inténtelo más tarde',
    ownConversationError: 'No puedes iniciar una conversación contigo mismo',
    modalCancelLabel: 'Cancelar',
    modalRequiredError: 'Este campo es obligatorio',
    chatModalTitle: 'Chatear con el vendedor',
    chatMessageLabel: 'Mensaje',
    chatMessagePlaceholder: 'Escribe tu mensaje para el vendedor',
    chatSubmitLabel: 'Enviar mensaje',
    reportModalTitle: 'Denunciar artículo',
    reportReasonLabel: 'Motivo de la denuncia',
    reportReasonPlaceholder: 'Explica el motivo de la denuncia',
    reportSubmitLabel: 'Enviar denuncia',
    reportReasonRequired: 'Debes indicar el motivo del reporte',
    reportSuccess: 'Se reportó el producto correctamente',
    sendMessageError: 'Error al enviar el mensaje',
    sendReportError: 'No se pudo enviar el reporte correctamente',
    favoriteError: 'Error al añadir a favoritos',
  },
} as const;
