export const MESSAGE_TEXT = {
  auth: {
    loginRequiredFields: 'Email y password son campos requeridos',
    loginInvalidCredentials: 'Email y/o Password incorrecto',
    resetRequiredFields: 'Email, usuario, nueva contraseña y repetir contraseña son campos requeridos',
    resetPasswordMismatch: 'Las contraseñas no coinciden',
    resetPasswordSuccess: 'Contraseña actualizada correctamente',
    resetPasswordError: 'No se pudo actualizar contraseña',
  },
  home: {
    categoriesLoadError: 'No se han podido cargar las categorías',
    latestProductsLoadError: 'No se han podido cargar los últimos productos',
    promotionProductsLoadError: 'No se han podido cargar los productos en promoción',
  },
  messages: {
    pageTitle: 'Mensajes',
    staffDescription: 'Reportes creados por los usuarios',
    userDescription: 'Tus conversaciones y respuestas de reportes',
    tabAll: 'Todos',
    tabPending: 'Pendiente',
    tabResolved: 'Resuelto',
    tabUnread: 'Sin leer',
    tabRead: 'Leído',
    loadingData: 'Cargando datos...',
    loadingConversation: 'Cargando conversación...',
    noReports: 'No hay reportes para mostrar.',
    noConversations: 'No hay conversaciones para mostrar.',
    loggedUserError: 'No se ha podido identificar al usuario logueado',
    unsupportedUserType: 'Tipo de usuario no soportado',
    loadDataError: 'No se han podido cargar los datos',
    defaultUser: 'Usuario',
    moderationContact: 'Moderación',
    reportPending: 'Reporte pendiente',
    reportResolved: 'Reporte resuelto',
    reportReasonPrefix: 'Motivo',
    reportResolutionPrefix: 'Resolución',
    articleFallbackPrefix: 'Artículo',
    now: 'Ahora',
    oneDayAgo: 'Hace 1 día',
    minutesAgo: 'Hace',
    hoursAgo: 'Hace',
    daysAgo: 'Hace',
    priceOfferLabel: 'Propuesta de precio',
    deliveryMethodLabel: 'Método de entrega',
    priceOfferPrompt: 'Introduce la propuesta de precio',
    priceOfferNumericError: 'La propuesta de precio solo puede contener números',
    deliveryMethodPrompt: 'Introduce el método de entrega',
    sendToComplainant: 'Enviar mensaje al denunciante',
    composerLabel: 'Mensaje',
    composerPlaceholder: 'Escribe un mensaje...',
    composerSendAria: 'Enviar mensaje',
    actionsAria: 'Acciones de conversacion',
    threadAria: 'Mensajes de la conversacion',
    emptyAria: 'Conversacion sin mensajes',
    conversationAria: 'Conversacion',
    proposePrice: 'Proponer precio',
    proposeDelivery: 'Proponer entrega',
    buy: 'Comprar',
    emptyConversation:
      'Inicia la conversación enviando un mensaje, haciendo una oferta de precio o proponiendo un método de entrega.',
  },
  articleDetail: {
    buyLoginRequired: 'Necesitas haber iniciado sesión para comprar un artículo',
    reserveLoginRequired: 'Necesitas haber iniciado sesión para reservar un artículo',
    messageLoginRequired: 'Debes iniciar sesión para enviar un mensaje',
    reportLoginRequired: 'Necesitas haber iniciado sesión para denunciar un artículo',
    favoriteLoginRequired: 'Necesitas haber iniciado sesión para añadir un artículo a favoritos',
    ownConversationError: 'No puedes iniciar una conversación contigo mismo',
    sellerMessagePrompt: 'Escribe tu mensaje para el vendedor:',
    reportReasonPrompt: 'Motivo del reporte:',
    reportReasonRequired: 'Debes indicar el motivo del reporte',
    sendMessageError: 'Error al enviar el mensaje',
    sendReportError: 'Error al enviar el reporte',
    favoriteError: 'Error al añadir a favoritos',
  },
} as const;
